substituicoes = [
    ('\n', ' \n '),
    (',', ' , '),
    (';', ' ; '),
    (':', ' : '),
    ('.', ' . '),
    ('(', ''),
    (')', ''),
    ('artigos ', 'artigo '),
    ('artigo ', 'art '),
    ('art.', 'art '),
    (' inciso ', ' '),
    (' inc ', ' '),
    (' viii ', ' oito '),
    (' iii ', ' tres '),
    (' ii ', ' dois '),
    (' iv ', ' quatro '),
    (' ix ', ' nove '),
    (' i ', ' um '),
    (' vii ', ' sete '),
    (' vi ', ' seis '),
    (' v ', ' cinco '),
    (' av ', ' avenida '),
    (' c c ', ' cc'),
    (' icms dec ', ' icms declarado '),
    (' meritisimo', ' meritissimo'),
    (' reembolso', ' pagamento'),
    ('apenas para reconhecer', 'para reconhecer'),
    ('com base no ', 'com fundamento no '),
    ('contra-razoes', 'contrarrazoes'),
    (' contra razoes', ' contrarrazoes'),
    ('da excipiente', 'do excipiente'),
    ('dilgencias', 'diligencias'),
    ('fazenda do estado de sao paulo', 'fesp'),
    ('fazenda publica do estado de sao paulo', 'fesp'),
    ('fazenda do estado', 'fazenda estadual'),
    ('lei no ', 'lei '),
    ('para o fim de reconhecer', 'para reconhecer'),
    ('presente ', ' '),
    ('publicacoes via diario oficial', 'publicacoes'),
    ('reintera', 'reitera'),
    ('reiterar ', 'reitera '),
    (' informar', ' informa'),
    ('requeremos', 'requer'),
    ('requerer', 'requer'),
    ('requer-se', 'requer'),
]

exclusoes = [
    'a',
    'agora',
    'alguem',
    'algum',
    'alguma',
    'algumas',
    'alguns',
    'ampla',
    'amplas',
    'amplo',
    'amplos',
    'ante',
    'antes',
    'ao',
    'aos',
    'apos',
    'aquela',
    'aquelas',
    'aquele',
    'aqueles',
    'aquilo',
    'as',
    # 'ate',
    'atraves',
    'cada',
    'coisa',
    'coisas',
    'com',
    'como',
    'contra',
    'contudo',
    'da',
    'da-',
    'daquele',
    'daqueles',
    'das',
    'de',
    'dela',
    'delas',
    'dele',
    'deles',
    'depois',
    'desde',
    'dessa',
    'dessas',
    'desse',
    'desses',
    'desta',
    'destas',
    'deste',
    'destes',
    'deve',
    'devem',
    'devendo',
    'dever',
    'devera',
    'deverao',
    'deveria',
    'deveriam',
    'devia',
    'deviam',
    'disse',
    'disso',
    'disto',
    'dito',
    'diz',
    'dizem',
    'do',
    'do(a)',
    'dos',
    'e',
    'e/ou',
    'ela',
    'elas',
    'ele',
    'eles',
    'em',
    'enquanto',
    'entre',
    'era',
    'eram',
    'eramos',
    'essa',
    'essas',
    'esse',
    'esses',
    'esta',
    'estamos',
    'estao',
    'estas',
    'estava',
    'estavam',
    'estavamos',
    'este',
    'esteja',
    'estejam',
    'estejamos',
    'estes',
    'esteve',
    'estive',
    'estivemos',
    'estiver',
    'estivera',
    'estiveram',
    'estiveramos',
    'estiverem',
    'estivermos',
    'estivesse',
    'estivessem',
    'estivessemos',
    'estou',
    'eu',
    'fazendo',
    'fazer',
    'feita',
    'feitas',
    'foi',
    'fomos',
    'for',
    'fora',
    'foram',
    'foramos',
    'forem',
    'formos',
    'fosse',
    'fossem',
    'fossemos',
    'fui',
    'grande',
    'grandes',
    'ha',
    'haja',
    'hajam',
    'hajamos',
    'hao',
    'havemos',
    'hei',
    'houve',
    'houvemos',
    'houver',
    'houvera',
    'houveram',
    'houveramos',
    'houverao',
    'houverei',
    'houverem',
    'houveremos',
    'houveria',
    'houveriam',
    'houveriamos',
    'houvermos',
    'houvesse',
    'houvessem',
    'houvessemos',
    'isso',
    'isto',
    'ja',
    'la',
    'lhe',
    'lhes',
    'lo',
    'mais',
    'mas',
    'me',
    'mesma',
    'mesmas',
    'mesmo',
    'mesmos',
    'meu',
    'meus',
    'minha',
    'minhas',
    'muita',
    'muitas',
    'muito',
    'muitos',
    'na',
    'nas',
    'nem',
    'nessa',
    'nessas',
    'nesta',
    'nestas',
    'ninguem',
    'no',
    'nos',
    'nossa',
    'nossas',
    'nosso',
    'nossos',
    'num',
    'numa',
    'o',
    'os',
    'ou',
    'outra',
    'outras',
    'outro',
    'outros',
    'para',
    'pela',
    'pelas',
    'pelo',
    'pelos',
    'pequena',
    'pequenas',
    'pequeno',
    'pequenos',
    'per',
    'perante',
    'pode',
    'podendo',
    'poder',
    'poderia',
    'poderiam',
    'podia',
    'podiam',
    'pois',
    'por',
    'porem',
    'porque',
    'posso',
    'pouca',
    'poucas',
    'pouco',
    'poucos',
    'presenca',
    'primeiro',
    'primeiros',
    'propria',
    'proprias',
    'proprio',
    'proprios',
    'quais',
    'qual',
    'quando',
    'quanto',
    'quantos',
    'que',
    'quem',
    'respeitosamente',
    's',
    'se',
    'seja',
    'sejam',
    'sejamos',
    'sempre',
    'sendo',
    'sera',
    'serao',
    'serei',
    'seremos',
    'seria',
    'seriam',
    'seriamos',
    'seu',
    'seus',
    'si',
    'sido',
    'so',
    # 'sob',
    'sobre',
    'somos',
    'sou',
    'sua',
    'suas',
    'talvez',
    'tambem',
    'tampouco',
    'te',
    'tem',
    'temos',
    'tendo',
    'tenha',
    'tenham',
    'tenhamos',
    'tenho',
    'ter',
    'tera',
    'terao',
    'terei',
    'teremos',
    'teria',
    'teriam',
    'teriamos',
    'teu',
    'teus',
    'teve',
    'ti',
    'tido',
    'tinha',
    'tinham',
    'tinhamos',
    'tive',
    'tivemos',
    'tiver',
    'tivera',
    'tiveram',
    'tiveramos',
    'tiverem',
    'tivermos',
    'tivesse',
    'tivessem',
    'tivessemos',
    'toda',
    'todas',
    'todavia',
    'todo',
    'todos',
    'tu',
    'tua',
    'tuas',
    'tudo',
    'ultima',
    'ultimas',
    'ultimo',
    'ultimos',
    'uma',
    'umas',
    'uns',
    'vendo',
    'ver',
    'vez',
    'vindo',
    'vir',
    'voce',
    'voces',
    'vos',
    'vossa',
]

pontuacoes = [
    ',',
    ';',
    ':',
    '.',
]
